Adding options for enabling and disabling the scene graph observer to listen to attach and detach events If this option is turned off, coordinate system events will not evoke scene graph observer callbacks. SceneGraph object will always output an empty tree.
This solution is sub-optimal solution. Since SceneGraphObserver is still being instantiated every time in the
igstkCoordinateSystemInterfaceMacros.h even if we don't want to use SceneGraph visualization functions.

It's forbidden in C++ to have derivatives within macros
Thus we can't use
#ifdef within that macro to switch on/off the SceneGraphObserver related code

It will generate Compiler Error C2121
'#' : invalid character : possibly the result of a macro expansion